FROM php:8.5.1-cli-alpine@sha256:55dc1dcc35c3a8e84406b90b3592634b78b4f5ed2505799d04f2cc4631d2d701

RUN apk update
RUN apk add git zip libzip-dev
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip

# Composer
# renovate: datasource=github-tags depName=composer/composer versioning=semver
ENV COMPOSER_VERSION="2.9.4"
RUN curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN chmod +x /usr/bin/composer
RUN composer self-update --clean-backups ${COMPOSER_VERSION}
