FROM php:8.1-cli-alpine@sha256:6c1fb5ac7a056e7590414257dcd60d795cc5882a435b76ef28036760ef8cd835

RUN apk update
RUN apk add git zip libzip-dev
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
