FROM php:8.4.26-cli-alpine@sha256:a5afbbcd1fb5264d3f9a90e4fd40616a12b696f41aedf4a24735808002099206

RUN apk update
RUN apk add git zip libzip-dev
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip

# Composer
# renovate: datasource=github-tags depName=composer/composer versioning=semver
ENV COMPOSER_VERSION="2.10.3"
RUN curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN chmod +x /usr/bin/composer
RUN composer self-update --clean-backups ${COMPOSER_VERSION}
