FROM php:8.2.17-cli-alpine@sha256:484aad684131a48cbef95ef7167cb1dde2e143480cc21dc9b2b919d7d12ea5d6

RUN apk update
RUN apk add git zip libzip-dev
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip

# Composer
# renovate: datasource=github-tags depName=composer/composer versioning=semver
ENV COMPOSER_VERSION="2.7.2"
RUN curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN chmod +x /usr/bin/composer
RUN composer self-update --clean-backups ${COMPOSER_VERSION}
